apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cal
  template:
    metadata:
      labels:
        app: flask-cal
    spec:
      containers:
      - name: flask-cal
        image: <ECR_IMAGE_PLACEHOLDER>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000



